name: CI/CD Pipeline

on:
  push:
    branches:
      - develop   # develop 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/kspot
            git reset --hard
            git pull origin develop

            cd /home/ubuntu/kspot
            chmod +x gradlew
            ./gradlew build -x test
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/kspot-0.0.1-SNAPSHOT.jar > app.log 2>&1 &
