name: CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build -x test

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ubuntu/kspot

            # 변경사항 반영
            git reset --hard
            git pull origin develop

            # Gradle 실행 권한
            chmod +x gradlew
            ./gradlew build -x test

            # 기존 실행 프로세스 종료 (포트 8080 사용 중이면 종료)
            PID=$(lsof -t -i:8080)
            if [ -n "$PID" ]; then
              echo "Stopping existing process $PID"
              kill -9 $PID
            fi

            # 새 애플리케이션 실행
            nohup java -jar -Dspring.config.location=file:/home/ubuntu/config/application.properties /home/ubuntu/kspot/build/libs/KSPOT-0.0.1-SNAPSHOT.jar --server.port=8080 --server.address=0.0.0.0 > /home/ubuntu/kspot/nohup.log 2>&1 &
            echo "Deployment complete"
